/**
 * Shared review data — used by TestimonialsSection (UI) and localBusinessJsonLd (schema.org).
 * Keep datePublished in YYYY-MM-DD format so JSON-LD remains valid.
 */
export const SALON_REVIEWS = [
  {
    name: 'Maria G.',
    service: 'Dip powder & pedicure',
    text: `I've been coming to this area for years — consistent quality and the pedi massage is amazing.`,
    rating: 5,
    datePublished: '2024-11-03',
  },
  {
    name: 'Taylor R.',
    service: 'Gel manicure',
    text: 'Super clean setup and my gel lasts forever. Easy to book and everyone is kind.',
    rating: 5,
    datePublished: '2024-12-18',
  },
  {
    name: 'Priya S.',
    service: 'Full set & nail art',
    text: `They took their time with the design. Best nail salon experience I've had in Phoenix.`,
    rating: 5,
    datePublished: '2025-01-09',
  },
  {
    name: 'Jordan M.',
    service: 'Waxing',
    text: 'Quick, professional, and comfortable. I always leave feeling put together.',
    rating: 5,
    datePublished: '2025-02-21',
  },
  {
    name: 'Elena V.',
    service: 'Spa pedicure',
    text: 'Walked in on a Saturday and they still accommodated me. Love the atmosphere.',
    rating: 5,
    datePublished: '2025-03-14',
  },
  {
    name: 'Ashley K.',
    service: 'Acrylic full set',
    text: 'My acrylics are flawless — exactly the shape and length I asked for. Will not go anywhere else!',
    rating: 5,
    datePublished: '2025-03-28',
  },
  {
    name: 'Brittany H.',
    service: 'Pedicure',
    text: 'The chairs are so comfortable and the staff is so sweet. Totally worth every penny.',
    rating: 5,
    datePublished: '2025-04-05',
  },
  {
    name: 'Samantha L.',
    service: 'Eyelash extensions',
    text: 'My lashes look so natural and full. I get compliments every single day. Thank you!',
    rating: 5,
    datePublished: '2025-04-12',
  },
  {
    name: 'Jessica T.',
    service: 'Gel-X nails',
    text: 'Love this place! Clean, friendly, and they never rush. My nails have never looked better.',
    rating: 5,
    datePublished: '2025-04-20',
  },
  {
    name: 'Rachel N.',
    service: 'Kids manicure & pedicure',
    text: 'Brought my daughter for her birthday — the staff made her feel like a princess. So sweet!',
    rating: 5,
    datePublished: '2025-04-30',
  },
  {
    name: 'Diana C.',
    service: 'Head spa',
    text: 'The head spa was the most relaxing thing I have done in years. I fell asleep! Highly recommend.',
    rating: 5,
    datePublished: '2025-05-07',
  },
  {
    name: 'Megan W.',
    service: 'Dip powder manicure',
    text: 'Three weeks later and still no chips. The dip powder lasts so much longer here than other places I have tried.',
    rating: 5,
    datePublished: '2025-05-15',
  },
  {
    name: 'Lauren F.',
    service: 'Nail art',
    text: 'Showed them a photo and they nailed it perfectly. Creative, patient, and so talented.',
    rating: 5,
    datePublished: '2025-05-22',
  },
  {
    name: 'Stephanie B.',
    service: 'Facial',
    text: 'My skin feels amazing after the facial. The esthetician explained every step — so professional.',
    rating: 5,
    datePublished: '2025-05-29',
  },
  {
    name: 'Amanda R.',
    service: 'Classic manicure',
    text: 'Best nail salon in North Phoenix, no question. Been coming for two years and the quality is always consistent.',
    rating: 5,
    datePublished: '2025-06-02',
  },
];
